require("init-option")
require("init-plugin")
require("init-keymaps")
require("init-colorscheme")
require("init-treesitter")
require("init-copilot")
require("init-lsp")
require("init-cmp")
require("init-dial") --C-a,C-x
require("init-neorg")
require("init-autocommants")
require("init-highstr") --highlig str
require("init-alpha")
require("init-hlslens")
-- require("init-navic")
require("init-numbers")
require("init-rust")
require("init-neoclips")
require("init-zenmode")
require("init-scroll")
require("init-escape")
require("init-fold")
require("init-todo")
require("init-indentline")
require("init-hop") --TODO learn
require("init-telescope")
require("init-autopairs")
require("init-troubles")
require("init-comment")
require("init-hlarg")
require("init-notify")
require("init-symboloutline")
require("init-dressing")
require("init-cursorline")
require("init-gitsigns")
require("init-nvimtree")
require("init-lastplace")
require("init-whichkey")
require("init-hydra")
require("init-impatient")
require("init-signature")
require("init-sniprun")
require("init-specs") --move cursor
require("init-bufferline")
require("init-lualine")
